AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Database

Parameters:

  EnvName:
    Default: nonprod
    Description: Env name
    Type: String

  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: mydb
    Description: My database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t3.small
    Description: DB instance class [db.t3.small, db.m5.large]
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
#  DBUsername:
#    NoEcho: 'true'
#    Description: Username for MySQL database access
#    Type: String
#    MinLength: '1'
#    MaxLength: '16'
#    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
#    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
#  DBPassword:
#    NoEcho: 'true'
#    Description: Password MySQL database access
#    Type: String
#    MinLength: '8'
#    MaxLength: '41'
#    AllowedPattern: '[a-zA-Z0-9]*'
#    ConstraintDescription: must contain only alphanumeric characters.

  SecretsStackName:
    Type: String

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: Postgres
      StorageType: gp2
      EngineVersion: '13.3'
      MasterUsername: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          -  !ImportValue
             'Fn::Sub': '${SecretsStackName}-MyRDSSecretDynamic'
          - ':SecretString:username}}'
      MasterUserPassword: !Join
        - ''
        - - '{{resolve:secretsmanager:'
          -  !ImportValue
            'Fn::Sub': '${SecretsStackName}-MyRDSSecretDynamic'
          - ':SecretString:password}}'
      MultiAZ: true
      Port: 5432
      PubliclyAccessible: true
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
