AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Params

Parameters:
  EnvName:
    Default: nonprod
    Description: Env name
    Type: String

Resources:
  Param1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param1-${EnvName}
      Value: 123
      Description: 'demo: test param 1'
      Type: String

  Param2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param2-${EnvName}
      Value: 123
      Description: 'demo: test param 2'
      Type: String

  Param3:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param3-${EnvName}
      Value: 123
      Description: 'demo: test param 2'
      Type: String

  Param4:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param4-${EnvName}
      Value: 123
      Description: 'demo: test param 2'
      Type: String

  Param5:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param5-${EnvName}
      Value: 123
      Description: 'demo: test param 2'
      Type: String

  Param6:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param4-${EnvName}
      Value: 123
      Description: 'demo: test param 2'
      Type: String
