AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Params

Parameters:
  EnvName:
    Default: nonprod
    Description: Env name
    Type: String

  SecretStackName:
    Default: experiments-secrets-nonprod
    type: String
    Description: stack name

Resources:
  Param1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param1-${EnvName}
      Value:
        Fn::ImportValue:
          !Sub ${SecretStackName}-MyRDSSecretStatic
      Description: 'demo: test param 1'
      Type: String

  Param2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub experiments-param2-${EnvName}
      Value:
        Fn::ImportValue:
          !Sub ${SecretStackName}-MyRDSSecretDynamic
      Description: 'demo: test param 2'
      Type: String

