AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Secrets

Parameters:
  EnvName:
    Default: nonprod
    Description: Env name
    Type: String

Resources:
  MyRDSSecretStatic:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub vitkuz-MyRDSSecretStatic-${EnvName}
      Description: Secrets for database
      SecretString: '{"username":"vitkuz","password":"123456789"}'
  MyRDSSecretDynamic:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub vitkuz-MyRDSSecretDynamic-${EnvName}
      Description: This secret has a dynamically generated secret password.
      GenerateSecretString:
        SecretStringTemplate: '{"username": "vitkuz"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

Outputs:
  MyRDSSecretStatic:
    Description: MyRDSSecretDynamic
    Value: !Ref MyRDSSecretDynamic
    Export:
      Name: !Sub ${AWS::StackName}-MyRDSSecretDynamic
